/**
 * MetaQS Analytics API
 *  * [**Real-Time API**](/metaqs-api/v1/docs) * [**LanguageTool API**](/metaqs-api/v1/languagetool/docs)     
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaterialFieldValidation } from './materialFieldValidation';


export interface MaterialValidationStats { 
    title?: MaterialFieldValidation;
    keywords?: MaterialFieldValidation;
    description?: MaterialFieldValidation;
    edu_context?: MaterialFieldValidation;
    subjects?: MaterialFieldValidation;
    license?: MaterialFieldValidation;
    ads_qualifier?: MaterialFieldValidation;
    material_type?: MaterialFieldValidation;
    object_type?: MaterialFieldValidation;
}

