/**
 * MetaQS Analytics API
 *  * [**Real-Time API**](/metaqs-api/v1/docs) * [**LanguageTool API**](/metaqs-api/v1/languagetool/docs)     
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MaterialFieldValidation { 
    missing?: Array<string>;
    too_short?: Array<string>;
    too_few?: Array<string>;
    lacks_clarity?: Array<string>;
    invalid_spelling?: Array<string>;
}

