/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type AppModelsLearningMaterialAttribute = 'properties.cclom:title' | 'properties.cclom:general_keyword' | 'properties.ccm:educationalcontext' | 'properties.ccm:taxonid' | 'properties.ccm:wwwurl' | 'properties.cclom:general_description' | 'properties.ccm:commonlicense_key';

export const AppModelsLearningMaterialAttribute = {
    Cclomtitle: 'properties.cclom:title' as AppModelsLearningMaterialAttribute,
    CclomgeneralKeyword: 'properties.cclom:general_keyword' as AppModelsLearningMaterialAttribute,
    Ccmeducationalcontext: 'properties.ccm:educationalcontext' as AppModelsLearningMaterialAttribute,
    Ccmtaxonid: 'properties.ccm:taxonid' as AppModelsLearningMaterialAttribute,
    Ccmwwwurl: 'properties.ccm:wwwurl' as AppModelsLearningMaterialAttribute,
    CclomgeneralDescription: 'properties.cclom:general_description' as AppModelsLearningMaterialAttribute,
    CcmcommonlicenseKey: 'properties.ccm:commonlicense_key' as AppModelsLearningMaterialAttribute
};

