/**
 * \"MetaQS API\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type AppModelsCollectionAttribute = 'properties.cm:title' | 'properties.cclom:general_keyword' | 'properties.cm:description' | 'parentRef.id';

export const AppModelsCollectionAttribute = {
    PropertiesCmtitle: 'properties.cm:title' as AppModelsCollectionAttribute,
    PropertiesCclomgeneralKeyword: 'properties.cclom:general_keyword' as AppModelsCollectionAttribute,
    PropertiesCmdescription: 'properties.cm:description' as AppModelsCollectionAttribute,
    ParentRefId: 'parentRef.id' as AppModelsCollectionAttribute
};

