/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type Attribute = 'properties.cclom:title' | 'properties.cclom:general_keyword' | 'properties.ccm:educationalcontext' | 'properties.ccm:taxonid' | 'properties.ccm:wwwurl' | 'properties.cclom:general_description' | 'properties.ccm:commonlicense_key';

export const Attribute = {
    Cclomtitle: 'properties.cclom:title' as Attribute,
    CclomgeneralKeyword: 'properties.cclom:general_keyword' as Attribute,
    Ccmeducationalcontext: 'properties.ccm:educationalcontext' as Attribute,
    Ccmtaxonid: 'properties.ccm:taxonid' as Attribute,
    Ccmwwwurl: 'properties.ccm:wwwurl' as Attribute,
    CclomgeneralDescription: 'properties.cclom:general_description' as Attribute,
    CcmcommonlicenseKey: 'properties.ccm:commonlicense_key' as Attribute
};

