/**
 * MetaQS API
 *  * [**Analytics API**](/metaqs-api/v1/analytics/docs) * [**LanguageTool API**](/metaqs-api/v1/languagetool/docs)     
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type CollectionAttribute = 'nodeRef.id' | 'type' | 'properties.cm:name' | 'permissions.Read' | 'properties.cm:edu_metadataset' | 'nodeRef.storeRef.protocol' | 'fullpath' | 'properties.cclom:general_keyword' | 'properties.ccm:educationalcontext' | 'i18n.de_DE.ccm:educationalcontext' | 'properties.cm:title' | 'properties.cm:description' | 'path' | 'parentRef.id';

export const CollectionAttribute = {
    NodeRefId: 'nodeRef.id' as CollectionAttribute,
    Type: 'type' as CollectionAttribute,
    PropertiesCmname: 'properties.cm:name' as CollectionAttribute,
    PermissionsRead: 'permissions.Read' as CollectionAttribute,
    PropertiesCmeduMetadataset: 'properties.cm:edu_metadataset' as CollectionAttribute,
    NodeRefStoreRefProtocol: 'nodeRef.storeRef.protocol' as CollectionAttribute,
    Fullpath: 'fullpath' as CollectionAttribute,
    PropertiesCclomgeneralKeyword: 'properties.cclom:general_keyword' as CollectionAttribute,
    PropertiesCcmeducationalcontext: 'properties.ccm:educationalcontext' as CollectionAttribute,
    I18nDeDeCcmeducationalcontext: 'i18n.de_DE.ccm:educationalcontext' as CollectionAttribute,
    PropertiesCmtitle: 'properties.cm:title' as CollectionAttribute,
    PropertiesCmdescription: 'properties.cm:description' as CollectionAttribute,
    Path: 'path' as CollectionAttribute,
    ParentRefId: 'parentRef.id' as CollectionAttribute
};

