/**
 * MetaQS API
 *  * [**Analytics API**](/metaqs-api/v1/analytics/docs) * [**LanguageTool API**](/metaqs-api/v1/languagetool/docs)     
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Collection { 
    noderef_id: string;
    type?: string;
    name?: string;
    title?: string;
    keywords?: Array<string>;
    description?: string;
    path?: Array<string>;
    parent_id?: string;
}

