/**
 * MetaQS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse200 { 
    /**
     * a language name like \'French\' or \'English (Australia)\'
     */
    name: string;
    /**
     * a language code like \'en\'
     */
    code: string;
    /**
     * a language code like \'en-US\' or \'ca-ES-valencia\'
     */
    longCode: string;
}

