/**
 * MetaQS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MaterialFieldValidation { 
    missing?: Array<string>;
    too_short?: Array<string>;
    too_few?: Array<string>;
    lacks_clarity?: Array<string>;
    invalid_spelling?: Array<string>;
}

