/**
 * \"MetaQS API\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaterialFieldValidation } from './materialFieldValidation';


export interface MaterialValidationStats { 
    title?: MaterialFieldValidation;
    keywords?: MaterialFieldValidation;
    subjects?: MaterialFieldValidation;
    description?: MaterialFieldValidation;
    educontext?: MaterialFieldValidation;
    license?: MaterialFieldValidation;
    ads_qualifier?: MaterialFieldValidation;
    material_type?: MaterialFieldValidation;
    object_type?: MaterialFieldValidation;
}

