/**
 * \"MetaQS API\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type MissingCollectionField = 'properties.cm:name' | 'properties.cm:title' | 'properties.cclom:general_keyword' | 'properties.cm:description';

export const MissingCollectionField = {
    Cmname: 'properties.cm:name' as MissingCollectionField,
    Cmtitle: 'properties.cm:title' as MissingCollectionField,
    CclomgeneralKeyword: 'properties.cclom:general_keyword' as MissingCollectionField,
    Cmdescription: 'properties.cm:description' as MissingCollectionField
};

