/**
 * MetaQS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type MissingMaterialField = 'properties.cm:name' | 'properties.cclom:title' | 'properties.cclom:general_keyword' | 'properties.ccm:educationalcontext' | 'properties.ccm:taxonid' | 'properties.ccm:wwwurl' | 'properties.cclom:general_description' | 'properties.ccm:commonlicense_key';

export const MissingMaterialField = {
    Cmname: 'properties.cm:name' as MissingMaterialField,
    Cclomtitle: 'properties.cclom:title' as MissingMaterialField,
    CclomgeneralKeyword: 'properties.cclom:general_keyword' as MissingMaterialField,
    Ccmeducationalcontext: 'properties.ccm:educationalcontext' as MissingMaterialField,
    Ccmtaxonid: 'properties.ccm:taxonid' as MissingMaterialField,
    Ccmwwwurl: 'properties.ccm:wwwurl' as MissingMaterialField,
    CclomgeneralDescription: 'properties.cclom:general_description' as MissingMaterialField,
    CcmcommonlicenseKey: 'properties.ccm:commonlicense_key' as MissingMaterialField
};

