/**
 * MetaQS API
 *  * [**Analytics API**](/metaqs-api/v1/analytics/docs) * [**LanguageTool API**](/metaqs-api/v1/languagetool/docs)     
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type MissingCollectionField = 'properties.cm:name' | 'properties.cm:title' | 'properties.cclom:general_keyword' | 'properties.cm:description';

export const MissingCollectionField = {
    Cmname: 'properties.cm:name' as MissingCollectionField,
    Cmtitle: 'properties.cm:title' as MissingCollectionField,
    CclomgeneralKeyword: 'properties.cclom:general_keyword' as MissingCollectionField,
    Cmdescription: 'properties.cm:description' as MissingCollectionField
};

