/**
 * \"MetaQS API\"
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type OehValidationError = 'missing' | 'too_short' | 'too_few' | 'lacks_clarity' | 'invalid_spelling';

export const OehValidationError = {
    Missing: 'missing' as OehValidationError,
    TooShort: 'too_short' as OehValidationError,
    TooFew: 'too_few' as OehValidationError,
    LacksClarity: 'lacks_clarity' as OehValidationError,
    InvalidSpelling: 'invalid_spelling' as OehValidationError
};

