/**
 * MetaQS API
 *  * [**Analytics API**](/metaqs-api/v1/analytics/docs) * [**LanguageTool API**](/metaqs-api/v1/languagetool/docs)     
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type ScoreModulator = 'linear' | 'square' | 'cube';

export const ScoreModulator = {
    Linear: 'linear' as ScoreModulator,
    Square: 'square' as ScoreModulator,
    Cube: 'cube' as ScoreModulator
};

